### ISSUE TITLE
Convert to a WebExtension

### ISSUE THREAD

**Issue by ExE-Boss** [meganz/firefox-extension#3]
In Firefox 57, Mozilla will be dropping legacy add-ons (SDK, XUL and XPCOM), and replacing them with the WebExtensions API.
This API is partially based off of Chrome’s extension API and is multi-process by design.

### MDN resources
https://developer.mozilla.org/en-US/Add-ons/WebExtensions
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Porting_a_Google_Chrome_extension
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Porting_a_legacy_Firefox_add-on

### Additional resources
https://blog.mozilla.org/addons/2016/11/23/add-ons-in-2017/
https://blog.mozilla.org/addons/2016/09/13/webextensions-and-parity-with-chrome/
https://wiki.mozilla.org/Add-ons/2017

---

Resolves #2

**Comment by cr-nz** [comment]
Many thanks for the information. The new WebExtension is now available from https://mega.nz/extensions. Or you can try auto updating from your installed legacy extension by going to the Tools menu -> Add-ons -> Right click on Mega -> Find Updates.

It will be maintained at https://github.com/meganz/firefox-web-extension from now on.
