### ISSUE TITLE
Extension breaks Firefox 56 beta 4 making it unusable

### ISSUE THREAD

**Issue by jomendoz** [meganz/firefox-extension#5]
Hi,

I was using Mega extension in Firefox 55 provided by ArchLinux [extra] repository without any problems.

Lately, I gave a try to Firefox 56 beta and after installing this extension, new tabs are unable to fetch content from the web. Making the browser unusable. Tracking down the reason, disabling Mega extension hit the nail.

As it has been said in [#3](https://github.com/meganz/firefox-extension/issues/3), I consider it's better to migrate to this new API.

Is there any roadmap and / or newcomer tasks that I can undertake?

Regards.

**Comment by florian2833z** [comment]
Yes, I have the same problem. The mega extension makes firefox 56 unusable, prevents pages from loading.

**Comment by jomendoz** [comment]
Are there any efforts to migrate this extention to the new standard WebExtensions?

**Comment by StudioMaX** [comment]
Same here. Unfortunately, I had to disable the extension.

**Comment by stephenjudge** [comment]
This extension has now been blocked in Firefox 56 by the Mozilla AMO team. 
The block report his here: https://blocked.cdn.mozilla.net/a84e6eba-4bc1-4416-b481-9b837d39f9f0.html
The bug report is here: https://bugzilla.mozilla.org/show_bug.cgi?id=1404290

**Comment by cr-nz** [comment]
Thanks for the report and sorry for the delay. The legacy version should have still worked until Firefox 57 so not sure why it stopped working properly in Firefox 56.

Anyway, the new WebExtension is now available from https://mega.nz/extensions. Or you can try auto updating from your installed legacy extension by going to the Tools menu -> Add-ons -> Right click on Mega -> Find Updates.

It will be maintained at https://github.com/meganz/firefox-web-extension from now on.
